# Generated by Django 3.2.19 on 2023-06-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('pets', '0004_alter_pet_slug'),
        ('photos', '0002_create_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='tagged_pets',
            field=models.ManyToManyField(blank=True, to='pets.Pet'),
        ),
    ]
