# Generated by Django 3.2.19 on 2023-06-08 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('pets', '0004_alter_pet_slug'),
        ('photos', '0004_alter_photos_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photos',
            new_name='Photo',
        ),
    ]
