# Generated by Django 3.2.19 on 2023-06-17 06:55

from django.db import migrations, models
import petstagram.photos.validators


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('photos', '0005_rename_photos_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='pet_photos/', validators=[petstagram.photos.validators.validate_image_less_than_5mb]),
        ),
    ]
