# Generated by Django 3.2.19 on 2023-06-07 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = ()

    operations = ()
